version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_react_typescript_container
    ports:
      - '4000:4000'
    volumes:
      - ./backend/:/backend/
      - ./backend/node_modules/
  frontend:
    build: ./frontend
    container_name: frontend_react_typescript_container
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/:/frontend
      - ./frontend/node_modules/
    stdin_open: true
